default_install_hook_types: ["pre-commit", "commit-msg", "post-checkout", "post-merge"]
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0  # Use the latest tagged release from https://github.com/JohnnyMorganz/StyLua/releases
    hooks:
      - id: stylua
        args: [--color, always]  # Optional: keep color output
        files: \.lua$  # Only run on .lua files
